SmartGameStatTrackingWebApp/Controllers/ProfilesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SmartGameStatTrackingWebApp.Models;

namespace SmartGameStatTrackingWebApp.Controllers
{
    public class ProfilesController : Controller
    {
        private SportsTrackDBContext db = new SportsTrackDBContext();

        // GET: Profiles/Details/5
        public ActionResult Details(string id)
        {
            if (User.Identity.Name == "")
            {
                return Redirect("/Login.aspx");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Profiles profiles = db.Profiles.Find(id);
            if (profiles == null)
            {
                return HttpNotFound();
            }
            return View(profiles);
        }

        [HttpPost]
        public ActionResult GetFlaggedAudio(int test)
        {
            var flaggedAudio = from audio in db.audio_File_Contents
                               where (audio.manual_control == true)
                               select audio;

            return Json(flaggedAudio);
        }

        [HttpPost]
        public ActionResult ClearFlag(int audio_id)
        {
            var flaggedAudio = db.audio_File_Contents.Find(audio_id);
            flaggedAudio.manual_control = false;
            db.Entry(flaggedAudio).State = EntityState.Modified;
            db.SaveChanges();

            return Json(flaggedAudio);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SmartGameStatTrackingWebApp/Views/Shared/_ControlSidebar.cshtml
<aside class="control-sidebar control-sidebar-dark">
    @* BEGIN Tabs *@
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
        <li class="active"><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
        <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    @* END Tabs *@
    <div class="tab-content">
        @* BEGIN Home Tab *@
        <div class="tab-pane active" id="control-sidebar-home-tab">
            <h3 class="control-sidebar-heading">Recent Activity</h3>
            <ul class="control-sidebar-menu">
                <li>
                    <a href="javascript::;">
                        <i class="menu-icon fa fa-birthday-cake bg-red"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

                            <p>Will be 23 on April 24th</p>
                        </div>
                    </a>
                </li>
            </ul>

            <h3 class="control-sidebar-heading">Tasks Progress</h3>
            <ul class="control-sidebar-menu">
                <li>
                    <a href="javascript::;">
                        <h4 class="control-sidebar-subheading">
                            Custom Template Design
                            <span class="pull-right-container">
                                <span class="label label-danger pull-right">70%</span>
                            </span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
                        </div>
                    </a>
                </li>
            </ul>
        </div>
        @* END Home Tab *@
        <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
        @* BEGIN Settings Tab *@
        <div class="tab-pane" id="control-sidebar-settings-tab">
            <form method="post">
                <h3 class="control-sidebar-heading">General Settings</h3>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Report panel usage
                        <input type="checkbox" class="pull-right" checked>
                    </label>

                    <p>
                        Some information about this general settings option
                    </p>
                </div>
            </form>
        </div>
        @* END Settings Tab *@
    </div>
</aside>
@* Add the sidebar's background. This div must be placed immediately after the control sidebar *@
<div class="control-sidebar-bg"></div>

SmartGameStatTrackingWebApp/Views/Shared/_Header.cshtml
<header class="main-header">
    <script type="text/javascript" src="~/Content/js/plugins/jquery/jquery-3.3.1.min.js"></script>
    @* BEGIN Logo *@
    <a href="@Url.Action("Index", "Home")" class="logo">
        @* Mini logo for sidebar 50x50 pixels *@
        <span class="logo-mini"><b>SG</b>S</span>
        @* Logo for regular state and mobile devices *@
        <span class="logo-lg"><b>SmartGame</b> Stats</span>
    </a>
    @* END Logo *@
    @* BEGIN Header *@
    <nav class="navbar navbar-static-top" role="navigation">
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                @* BEGIN User Account Menu *@
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-user" alt ="User Image"></i>
                        <span class="hidden-xs">@User.Identity.Name</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="user-header" style="min-height:0px">
                            <p>
                                @User.Identity.Name
                            </p>
                        </li>
                        <li class="user-footer">
                            <div class="pull-left">
                                <input class="btn btn-default btn-flat" type="button" value="Profile" onclick="location.href='@Url.Action("Details", "Profiles", new { id = User.Identity.Name })'" />
                            </div>
                            <div class="pull-right">
                                <a href="~/Login.aspx" class="btn btn-default btn-flat sign-out">Sign out</a>
                            </div>
                        </li>
                    </ul>
                </li>
                @* END User Account Menu *@
            </ul>
        </div>
    </nav>
</header>

<script type="text/javascript">
    $('.sign-out').click(function () {
        $.ajax({
            type: 'POST',
            url: '/Home/SignOut',
            datatype: 'json',
            success: function (data) {

            }
        });
    });
</script>

SmartGameStatTrackingWebApp/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
@using WebHelpers.Mvc5.Enum
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>
        @if (!string.IsNullOrWhiteSpace(ViewBag.Title))
        {
            @ViewBag.Title@: -
        }
        Sports Stat Tracking
    </title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    @Styles.Render("~/Bundles/css")
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
        @Html.Partial("_Header")
        @Html.Partial("_Sidebar")

        <div class="content-wrapper">
            <section class="content-header">
                <h1>
                    @ViewBag.Title
                    <small>@ViewBag.Description</small>
                </h1>
            </section>

            <section class="content">
                @RenderBody()
            </section>
        </div>

        @Html.Partial("_ControlSidebar")
    </div>

    <script src="@RouteJs.RouteJsHandler.HandlerUrl"></script>
    <script src="@EnumHandler.HandlerUrl"></script>
    @Scripts.Render("~/Bundles/js")
    @RenderSection("ViewSpecificJavascript", required: false)
</body>
</html>

SmartGameStatTrackingWebApp/Views/Shared/_Sidebar.cshtml
@using WebHelpers.Mvc5
<aside class="main-sidebar">
    <section class="sidebar">
        @* BEGIN Menu *@
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header">Navigate</li>
            <li class="@Url.IsLinkActive("Index", "Home")">
                <a href="@Url.Action("Index", "Home")"><i class="fa fa-home"></i> <span>Home</span></a>
            </li>
            <li class="@Url.IsLinkActive("Index", "Games")">
                <a href="@Url.Action("Index", "Games")"><i class="fa fa-archive"></i> <span>Games</span></a>
            </li>
            <li class="@Url.IsLinkActive("Index", "Teams")">
                <a href="@Url.Action("Index", "Teams")"><i class="fa fa-group"></i> <span>Teams</span></a>
            </li>
            <li class="@Url.IsLinkActive("Index", "Players")">
                <a href="@Url.Action("Index", "Players")"><i class="fa fa-user-o"></i> <span>Players</span></a>
            </li>
        </ul>
        @* END Menu *@
    </section>
</aside>